### ISSUE TITLE
Script Error - Cannot download subtitles from subcenter

### ISSUE THREAD

**Issue by jossef** [XBMCil/service.subtitles.subscenter#1]
this is what i saw in `~/.kodi/temp/kodi.log`

```
12:10:13 T:2551163712  NOTICE: -->Python Interpreter Initialized<--
12:10:14 T:2551163712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: must be string or buffer, not None
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/service.subtitles.subscenter/service.py", line 152, in <module>
                                                subs = download(params["id"], params["language"], params["link"], params["filename"])
                                              File "/home/user/.kodi/addons/service.subtitles.subscenter/service.py", line 62, in download
                                                helper.download(id, language, key, filename, zip_filename)
                                              File "/home/user/.kodi/addons/service.subtitles.subscenter/resources/lib/SUBUtilities.py", line 247, in download
                                                subFile.write(f)
                                            TypeError: must be string or buffer, not None
                                            -->End of Python script error report<--
12:10:14 T:2523913024   ERROR: GetDirectory - Error getting plugin://service.subtitles.subscenter/?action=download&link=bf23f47bb198e2cdb8e5e6e80fa974dd&id=35741&filename=Breaking.Bad.S02E05.HDTV.XviD-FQM&language=he
12:15:24 T:2845825856  NOTICE: script.tv.show.next.aired: ### no prior data found

```

maybe subcenter changed something in the download url. i will debug it later on

**Comment by jossef** [comment]
#### seems like subcenter is broken

e.g. http://subscenter.cinemast.com/he/subtitle/search/?q=%D7%A9

damn it :dash: . 

---

debugged it, the url for download is:

```
http://www.subscenter.org/he/subtitle/download/he/260209/?key=80e3a85edc4abefaf8706593182ed048&v=Breaking.Bad.S02E05.720p.Bluray.x264-CLUE
```

![image](https://cloud.githubusercontent.com/assets/1287098/7665619/71c9811a-fbc9-11e4-8d6f-0b85c193a5a4.png)

**Comment by CaTzil** [comment]
If the site is not working there id nothing I can do.
Try to use alternative sites. (ktuvit)
