### ISSUE TITLE
Error when downloading subtitle

### ISSUE THREAD

**Issue by bartzy** [XBMCil/service.subtitles.subscenter#6]
Hi,

Thanks for the great plugin.

I've encountered an error downloading subtitles in the last few days. Search is working successfully but when downloading I get an error. This is the relevant log output:

```
13:13:04 T:7576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: must be string or buffer, not dict
                                            Traceback (most recent call last):
                                              File "C:\Users\bartz\AppData\Roaming\Kodi\addons\service.subtitles.subscenter\service.py", line 156, in <module>
                                                subs = download(params["id"], params["language"], params["link"], params["filename"])
                                              File "C:\Users\bartz\AppData\Roaming\Kodi\addons\service.subtitles.subscenter\service.py", line 62, in download
                                                helper.download(id, language, key, filename, zip_filename)
                                              File "C:\Users\bartz\AppData\Roaming\Kodi\addons\service.subtitles.subscenter\resources\lib\SUBUtilities.py", line 278, in download
                                                subFile.write(f)
                                            TypeError: must be string or buffer, not dict
                                            -->End of Python script error report<--
13:13:05 T:7408   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://service.subtitles.subscenter/?action=download&link=ffe385039814935b04c7400d27b2405e&id=281704&filename=Better.Call.Saul.S02E03.720p.HDTV.x264-AVS&language=he
```

Thanks!

**Comment by CaTzil** [comment]
Its a known issue with the site API.
Site owner was addressed about that issue.

**Comment by bartzy** [comment]
Thanks. Do you know if they're working on it?

**Comment by CaTzil** [comment]
7a013ebce1ee368953436590033840bf2cdf446f fixes the issue.

**Comment by bartzy** [comment]
Awesome, thanks!
